### ISSUE TITLE
DockerHub as a src registry

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes-sigs/k8s-container-image-promoter#9]
After doing some research about how time consuming would be to implement DockerHub as a src registry I think there are three paths we can take.

1. Current implementation use `gcloud` CLI tool for work related registries, so we could create a simple, similar CLI tool with the same API related to commands we need (I think it's the quickest way)
2. Create an abstraction just for DockerHub without using any CLI tool, where it would coexist with current implementation for GCR (GCR would use `gcloud` tool and DockerHub would send direct requests to its REST API) [quite time consuming].
3. Create an abstraction from the ground up which will be communicating with any Docker Container Registry via REST API (it's the most time-consuming option, because we have to figure out how to handle different ways of auth and I assume your decision of use `gcloud` instead of just calling API was due of that)

I looked into: https://github.com/google/go-containerregistry which would be a nice tool to use, but there are no features related to registry like listing of repositories etc., so there would be need to implement them.

It would be good to talk about it, because maybe there are other ways I couldn't see. Irrespective of decision I would love to implement the changes. :-)

Bart

**Comment by listx** [comment]
First, thank you so much for looking into this area. I agree with your 3 paths you outlined.

The main reason I chose to use `gcloud` was because it allowed me to ignore everything related to authentication (I just assume that the service account specified in the promoter manifest is already authenticated), because I wanted to get this tool out and working asap.

You are right that the go-containerregistry doesn't really support the features we need (esp. regarding manifest lists, as I stated in #7).

I think (1) will add unnecessary complexity (we would now need 2 tools...?). IMHO (2) is the best choice for now. At some point down the road, I'm sure we would move away from gcloud as well and just use pure REST calls directly as it is cleaner (no need to worry about spawning another process and hook up the stdout pipes to it and such). The other issue with gcloud I noticed is that it prints informational messages to stderr, which is a little bit confusing.

Going with (3) would be even better, but I agree that it would be time consuming. Although, to be fair, with #7 we still need to use REST calls anyway (or at least move to using `curl` instead of `gcloud`).
